name: Update Dev Branch

on:
  push:
    branches: [main]
    
permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        env:
          USER: ${{ secrets.USER }}
          MAIL: ${{ secrets.MAIL }}
        run: |
          git config user.name "$USER"
          git config user.email "$MAIL"

      - name: Update Dev Branch
        run: |
          git checkout main
          git fetch origin
          git checkout dev
          git pull
          git merge origin/main
          git push origin dev
